### ISSUE TITLE
Hi yipin, about re-implement your project

### ISSUE THREAD

**Issue by bbklk** [twopin/CAMP#17]
Dear Yipin, I wish to re-implement CAMP, but the code you provided here is not complete. If possible, could you please upload the full version of the code or detailed instructions for your implementation? The Nat. Comm. paper you published is very nice, but you need to make it replicable to promote your achievement. Look forward to your reply.

If the process is too complex, I can totally understand it, and I am willing to pay for your effort, please send me your Wechat ID or email address.

**Comment by twopin** [comment]
Hi, thank you for your interest in our work. For the code part of our work, we already upload the complete core codes here. However, I admit there are several gaps between each step, which are due to the external tools for feature generation (e.g., you need to download other bioinformatic tools to generate sequence-based features and then go back to the downstreaming python codes). If you have any questions about implementing the codes, you can email me via twopinlei@hotmail.com. For the data parts, since we used commercial database DrugBank, we cannot directly provide the data here. Instead, we provide workflows and procedures to curate the dataset if you already have permission to get access to DrugBank DB.
