### ISSUE TITLE
error in CAMP_BS.h5 modelling

### ISSUE THREAD

**Issue by xiaoxiao349** [twopin/CAMP#33]
Hi when I use CAMP_BS.h5 for prediction I got this error. Could you please give some advice on it?
![image](https://user-images.githubusercontent.com/72723852/222907857-9efa5a80-75e4-45d1-a1d3-9ad73556701a.png)

**Comment by denizozcivi** [comment]
Hi Dear, how did you run the application? Can you please give advice to us?

**Comment by twopin** [comment]
Hi, what the input size you fed into the model?

**Comment by xiaoxiao349** [comment]
> Hi, what the input size you fed into the model?

Hi twopin thanks for replying, I input 6 protein and peptide sequence and got the 8 files after preprocessing (protein_feature_dict, peptide_feature_dict, ...). Using the function load_example I got [X_pep, X_p, X_SS_pep, X_SS_p, X_2_pep, X_2_p, X_dense_pep, X_dense_p, pep_sequence, prot_sequence, X_pep_mask, X_bs_flag]. I'm not sure what is the input size though.

**Comment by twopin** [comment]
Hi, I hope the discussion yesterday can solve your concerns. There are several  key points may cause the difference: 1. the SS feature you generated are derived from different version of SCRATCH, after comparing we noticed that there are many differences; 2. Although we used the same PDDbench list, we used different sampling methods to generate negatives. 3. CAMP adopts UniProt sequences instead of PDB fasta sequences. 4. The Intrinsic Disorder values are different. To solve these problems, I already send you my PDDbench data (including negatives), my inference results and evaluation scripts. Hope these stuff can help you.
